### ISSUE TITLE
Some dsk not working

### ISSUE THREAD

**Issue by nonochus** [tdlabac/MSX1_MiSTer#12]
Hello, I have tried some dumps in dsk formats from this page:

https://msxcas.webcindario.com/

Many dynamic games that in theory should work on an msx1,crash, to name a few, after the war, jabato or cozumel and other opera soft games like la abadia del crimen or the mutant zone, don't work.

I can try all and make a specific list. I've also tried booting the core by pressing the CTRL key to release as much memory as possible and they still don't work.

A bug in the disk controller?  Maybe it lacks ram? If so, would it be possible to add an option in the core so that it has more ram?
This would be fine for the CAS SWIV format game that asks for 128k ram to run. It would be nice to have a choice of 64k and 128k.

Excellent core, I love it! Thank you very much

**Comment by GuerreroNinja** [comment]
Can you please detail which DSKs from that page don't work on your tests so I can have a look at them? Please note that no MSX 1 had more than 64Kb of RAM, so more RAM won't help at all. 

IMPORTANT: Lots of DSK "conversions" of tapes were intended for MSX 2 specific models (usually, NMS 8235/8245 and Sony HB-F700) so they had loaders for their memory configuration. Those loaders may fail on Philips VG 8020, which is the computer implemented by the core. This affects specially to Dinamic and other tape titles, so it is better to use CAS files instead of discs (or try recopilations like MSXMANIA, they usually are more MSX 1 friendly than others unknown user dumps). To check it, first try to load the CAS file (tape option), then try the DSK. If the game in CAS works OK, and the DSK no, probably the loader is not compatible with the VG 8020 machine, so the core is working as expected. You can check the loader usually inspecting Autoxec.bat or Autoexec.bas (or the loader in disc). Those incompatibilities were very common on real MSX machines.

**Comment by nonochus** [comment]
Yes, this dsk are more for msx2, closing the issue.
